import { CalendarDays, Clock } from 'lucide-react';
export const horariosItinerarios = [
  {
    titulo: 'Dias Úteis',
    icone: <Clock className="size-6 text-white" />,
    linhas: [
      { numero: '01', nome: 'Boqueirão' },
      { numero: '02', nome: 'Cascavel' },
      { numero: '03', nome: 'Santana' },
      { numero: '04', nome: 'Primavera' },
      { numero: '05', nome: 'Bandeirantes Via Rodoviária' },
      { numero: '06', nome: 'Vila Carli' },
      { numero: '07', nome: 'Pérola do Oeste' },
      { numero: '09', nome: 'Ayrton Senna' },
      { numero: '10', nome: 'Vila Bela' },
      { numero: '11', nome: 'Santa Cruz' },
      { numero: '15', nome: 'Aeroporto' },
      { numero: '17', nome: 'Tancredo Neves' },
      { numero: '19', nome: 'Col. Agrícola Via Rodoviária' },
      { numero: '21', nome: 'São João' },
      { numero: '22', nome: 'Jardim das Américas' },
      { numero: '23', nome: 'Mattos Leão' },
      { numero: '24', nome: 'Jordão' },
      { numero: '27', nome: 'Interbairros' },
      { numero: '28', nome: 'Boqueirão Via Guaira' },
      { numero: '31', nome: 'Jardim Américas Paz e Bem' },
      { numero: '33', nome: 'CEDETEG' },
      { numero: '34', nome: 'Coamo' },
      { numero: '36', nome: 'Residencial 2000' },
      { numero: '38', nome: 'Jardim Moriá' },
      { numero: '40', nome: 'Jardim Dona Ângela' },
      { numero: '45', nome: 'São Cristóvão' },
      { numero: '46', nome: 'Unicentro' },
      { numero: '48', nome: 'Cristo Rei' },
      { numero: '49', nome: 'Jardim Patrícia' },
      { numero: '50', nome: 'UTFPR-Shopping' },
      { numero: '52', nome: 'Tancredo Neves Ayrton Senna' },
      { numero: '53', nome: 'Jardim Pinheirinho' },
    ],
  },
  {
    titulo: 'Sábados',
    icone: <Clock className="size-6 text-white" />,
    linhas: [
      { numero: '02', nome: 'Cascavel' },
      { numero: '07', nome: 'Pérola do Oeste' },
      { numero: '13', nome: 'Coronelinho Via Guaira' },
      { numero: '14', nome: 'Sol Poente Feroz II Via Guaira' },
      { numero: '19', nome: 'Col. Agrícola Via Rodoviária' },
      { numero: '22', nome: 'Jardim das Américas' },
      { numero: '28', nome: 'Boqueirão Via Guaira' },
      { numero: '34', nome: 'Coamo' },
      { numero: '36', nome: 'Residencial 2000' },
      { numero: '50', nome: 'UTFPR-Shopping' },
    ],
  },
  {
    titulo: 'Domingos e Feriados',
    icone: <CalendarDays className="size-6 text-white" />,
    linhas: [
      { numero: '01', nome: 'Interbairros' },
      { numero: '02', nome: 'Interbairros' },
      { numero: '05', nome: 'Bandeirantes via Rodoviária' },
      { numero: '07', nome: 'Interbairros' },
      { numero: '08', nome: 'Interbairros' },
      { numero: '09', nome: 'Interbairros' },
      { numero: '19', nome: 'Colégio Agrícola via Rodoviária' },
      { numero: '22', nome: 'Jardim das Américas Paz e Bem' },
      { numero: '36', nome: 'Residencial 2000' },
    ],
  },
];
